name: Coverage Badge

on:
  push:
    branches:
      - main  # Change to your default branch name if it's not 'main'

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust if you use a different file

      - name: Run coverage badge script
        run: |
          python tests/codecoverage.py  # Replace with the actual path

      - name: Run pylint badge script
        run: |
          python tests/pylint-badge.py  # Replace with the actual path
 
